"""pdf_export.py — Generate a formatted PDF from a chat session."""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER

def generate_pdf(source_url: str, messages: list[dict]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle("Title2", parent=styles["Title"],
                                  fontSize=20, textColor=colors.HexColor("#6c63ff"),
                                  spaceAfter=6)
    sub_style   = ParagraphStyle("Sub", parent=styles["Normal"],
                                  fontSize=10, textColor=colors.HexColor("#64748b"),
                                  spaceAfter=4)
    q_style     = ParagraphStyle("Q", parent=styles["Normal"],
                                  fontSize=11, textColor=colors.HexColor("#6c63ff"),
                                  fontName="Helvetica-Bold", spaceAfter=4,
                                  leftIndent=0)
    a_style     = ParagraphStyle("A", parent=styles["Normal"],
                                  fontSize=11, textColor=colors.HexColor("#1a1a2e"),
                                  spaceAfter=4, leftIndent=12,
                                  leading=16)
    src_style   = ParagraphStyle("Src", parent=styles["Normal"],
                                  fontSize=9, textColor=colors.HexColor("#94a3b8"),
                                  leftIndent=12)

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph("🤖 RAG Chatbot — Session Export", title_style))
    story.append(Paragraph(f"Website: <b>{source_url}</b>", sub_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", sub_style))

    qa_pairs = []
    i = 0
    msgs = [m for m in messages if isinstance(m, dict)]
    while i < len(msgs):
        if msgs[i].get("role") == "user":
            q = msgs[i]["content"]
            a = msgs[i+1]["content"] if i+1 < len(msgs) and msgs[i+1].get("role") == "assistant" else ""
            sources = msgs[i+1].get("sources", []) if i+1 < len(msgs) else []
            if isinstance(sources, str):
                import json
                try: sources = json.loads(sources)
                except: sources = []
            qa_pairs.append((q, a, sources))
            i += 2
        else:
            i += 1

    story.append(Paragraph(f"Total Questions: <b>{len(qa_pairs)}</b>", sub_style))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#6c63ff")))
    story.append(Spacer(1, 0.5*cm))

    # ── Q&A ───────────────────────────────────────────────────────────────────
    for idx, (q, a, sources) in enumerate(qa_pairs, 1):
        story.append(Paragraph(f"Q{idx}: {q}", q_style))
        # Clean answer text for PDF
        a_clean = a.replace("**", "").replace("*", "").replace("`", "")
        for line in a_clean.split("\n"):
            if line.strip():
                story.append(Paragraph(line.strip(), a_style))
        if sources:
            story.append(Paragraph(f"Sources: {' | '.join(sources[:2])}", src_style))
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
        story.append(Spacer(1, 0.3*cm))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph("Generated by RAG Website Chatbot", sub_style))

    doc.build(story)
    return buf.getvalue()